### ISSUE TITLE
Still need context.ClearHandler if use net/http context?

### ISSUE THREAD

**Issue by mytc** [gorilla/sessions#121]
I am little confused about the `context.ClearHandler ` . The documentation stated that:

> Important Note: If you aren't using gorilla/mux, you need to wrap your handlers with context.ClearHandler as or else you will leak memory! An easy way to do this is to wrap the top-level mux when calling http.ListenAndServe

In fact I am using net/http instead of gorilla/mux, and net/http context (go 1.8) but the documentation also stated : 

> The ClearHandler function is provided by the gorilla/context package.

Do I still need to use it?

**Comment by elithrar** [comment]
You don’t need to use mux.ClearHandler if you aren’t using gorilla/mux or
gorilla/context 😉

**Comment by mytc** [comment]
Awesome! Thanks

**Comment by eliveikis** [comment]
@elithrar Can you please clarify? The questions was if `context.ClearHandler` should be used, not `mux.ClearHandler`. Do you mean gorilla/mux *and* gorilla/context? We are using "gorilla/session" with the github.com/go-chi/chi router.

We use only 2 functions from gorilla/context:

- `sessions.NewCookieStore`
- `sessions.CookieStore.Get`

It looks like we still need the `context.ClearHandler`, since `sessions.CookieStore.Get` receives the `http.Request` which calls `sessions.GetRegistry` which sets the context in the global map in gorilla/context:
```
context.Set(r, registryKey, newRegistry)
```
As described here:
https://github.com/gorilla/sessions/issues/55

Thank you

**Comment by 1ambda** [comment]
Curious too. I am using go-swagger for http handling layer and want to use `gorilla/sessions`. But 

this sentence conflicts with
> You don’t need to use mux.ClearHandler if you aren’t using gorilla/mux or gorilla/context 😉

the description in README.md

>  If you aren't using gorilla/mux, you need to wrap your handlers with context.ClearHandler or else you will leak memory!

**Comment by elithrar** [comment]
You SHOULD wrap your top level router/handler with context.ClearHandler if
you are using sessions on its own.
