### ISSUE TITLE
securecookie: the value is not valid

### ISSUE THREAD

**Issue by danvonk** [gorilla/sessions#16]
Hi,
I get this error when trying to call store.Get() on a request from websocket.Conn.Request()

```
session, err := store.Get(conn.Request(), "my_session")
```

The error originates from the verifyMac function of gorilla/securecookie.

**Comment by dominichamon** [comment]
I'm seeing this too and would love to know how to clear it/solve it.

**Comment by elithrar** [comment]
Is the error behavior consistent? Or does it only affect some requests?

**Comment by dominichamon** [comment]
I was able to mitigate this by returning a valid page when I hit the error (instead of a 500) and then deleting the cookie manually from the browser. I think it's caused by me updating the auth/encrypt keys but having a cookie on the browser side from an existing session.

i don't know what the right way to mitigate this is in the long-term, so any advice is welcome.

**Comment by kisielk** [comment]
If you you want to avoid this you need a way for your application to migrate keys.

**Comment by nucleartide** [comment]
I ran into this issue too. I ended up just ignoring the error, since the [gorilla/sessions docs](http://www.gorillatoolkit.org/pkg/sessions#CookieStore.Get) say that a new session is still returned. Afterward, you can still call `session.Save()` and the requesting browser will now have a new, valid session cookie.

**Comment by johnbalvin** [comment]
I was facing the same issue and it was a lit bit difficult to spot at first, the problem is that I had
`var store = sessions.NewCookieStore(securecookie.GenerateRandomKey(10))`
so each time I restart the server, a new key for the store is been generated, and if you previously have saved the cookie into web browser, then it would cause an error when trying to decode the cookie because it is using the new key and not the key when the cookie was created at first.
This could be an issue difficult to spot even worst when deploying into kubernetes, because sometimes a node(machine) needs to restart and that node will generate it´s own key and that could cause a conflict with the others nodes. I would recommend not to generate a random key, instead, insert manually a key so you won´t face that issue, like:
`var store = sessions.NewCookieStore([]byte("asdaskdhasdhgsajdgasdsadksakdhasidoajsdousahdopj"))`

**Comment by elithrar** [comment]
You shouldn't embed keys/credentials into your source code. Instead, you should pass them in via the environment - e.g. `os.Getenv("APPNAME_SESSION_KEY")`. That environment may be bootstrapped by your deployment system - in the k8s case, using the Secrets functionality: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

**Comment by johnbalvin** [comment]
I think I can live with my solution for now, as I´m working alone, that´s why I can just generate manually the key and because I´m newbie at kubernetes and I wouldn´t wanna break nothing for now.

**Comment by colminator** [comment]
> I ran into this issue too. I ended up just ignoring the error, since the [gorilla/sessions docs](http://www.gorillatoolkit.org/pkg/sessions#CookieStore.Get) say that a new session is still returned. You can still call `session.Save()`, and afterward the requesting browser will have a new, valid session cookie.

In general it is a bad practice to use something if an error is encountered. The `securecookie` pkg does have the specific error `securecookie.ErrMacInvalid`- which will occur when keys have been changed and the HMAC cookie decoding fails. This is the correct way to identify a bad cookie from some other internal error (e.g. if a `FileSystemStore` is being used and there's an i/o error.)

**Comment by RubenGarcia** [comment]
I am also affected due a long keycloak token.

**Comment by SharkFourSix** [comment]
> You shouldn't embed keys/credentials into your source code. Instead, you should pass them in via the environment - e.g. `os.Getenv("APPNAME_SESSION_KEY")`. That environment may be bootstrapped by your deployment system - in the k8s case, using the Secrets functionality: https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

You should also be cautious using ENV variables because on linux you do not need sudo privileges to peek into other process's ENV variables. :wink:. Meaning anyone that can list processes on an instance can easily grab those secrets without needing to have access to the .ENV file.

**Comment by panbanda** [comment]
I just rename/version the cookie when changing encryption / signing keys.
