### ISSUE TITLE
how to store objects in session?

### ISSUE THREAD

**Issue by qibobo** [gorilla/sessions#162]
Per my understanding to the session package, "CookieStore" will save session to http cookie and "FilesystemStore" save session to the filesystem. So there is no default implementation that store the session to server memory?

**Comment by elithrar** [comment]
There is no MemoryStore, no.

This is because it’s extremely brittle—losing all sessions because you
re-deployed the process—and all stores still issue some kind of cookie.

There are a number of backend store implementations (Redis, Memcached, etc)
that are better suited to that purpose:
https://github.com/gorilla/sessions/blob/master/README.md

**Comment by elithrar** [comment]
Closing, but feel free to continue asking questions.
