### ISSUE TITLE
Why does FilesystemStore use securecookie? [question] 

### ISSUE THREAD

**Issue by FiloSottile** [gorilla/sessions#200]
When the actual session is not stored in a cookie, and the ID is unpredictable (that is, generated from at least 16 bytes extracted from crypto/rand), it should be ok to store the naked ID in a cookie, and use it to lookup sessions in the store.

In fact, the main advantage of a non-cookie session store is that it doesn't require any key management, because there's a trusted server-side storage.

Why does FilesystemStore still use securecookie? It looks like most other Store implementations copied FilesystemStore and also require keys, when they could avoid that.

**Comment by elithrar** [comment]
It’s a good question, and one I’ve considered before, since (as you say) a
sufficiently long & cryptographically random ID as a cookie value doesn’t
need to be further signed.

N.B: I didn’t author the API as-is.

But saying that: it’s also part of the public API, and “not worth” changing
until we revisit the entire package (simplifying the crypto for cookie
storage, interfaces, etc) in a breaking v2. I could technically ignore
unnecessary keyPairs today, but that risks breaking users’ tests and isn’t
worth the trade-off.

**Comment by idc77** [comment]
But if the session id somehow manages to get leaked then for security reasons it would be better so have the cookie value encrypted.
