### ISSUE TITLE
[question] How best to distinguish errors returned by store.Get(r, "name").

### ISSUE THREAD

**Issue by MichaelHipp** [gorilla/sessions#209]
This snippet of code appears several times in the docs:
```
    // Get a session. Get() always returns a session, even if empty.
    session, err := store.Get(r, "session-name")
    if err != nil {
        http.Error(w, err.Error(), http.StatusInternalServerError)
        return
    }
```
If the store is unable to complete the Get() call it will return InternalServerError. But this call also fails if the session is expired. Sending InternalServerError implies the client should just retry the request later. But on an expired session this is futile. How is the best way to distinguish between actual  "internal" server errors vs "rejected cookie/session"?

**Comment by juburr** [comment]
Agreed, `store.Get()` has somewhat unexpected error handling behavior.

For example, with `FilesystemStore`, a session that doesn't exists will throw error that says `open {session_filename_here}: no such file or directory` instead of an error type that indicates an expired or invalid session. It's trying to open that file because a user  supplied an old or invalid session ID in the cookie they supplied.
