### ISSUE TITLE
[question] What happened to V2?

### ISSUE THREAD

**Issue by restourgie** [gorilla/sessions#229]
In the issue history I saw promising discussions regarding v2 of gorilla/sessions. It looks like everything is in maintenance mode and the gorilla website has been showing quirks (gorillatoolkit.org/packages). What are the plans for gorilla? Are programmers needed to contribute?

**Comment by elithrar** [comment]
Creating a v2 in Go is a non-trivial undertaking - this article gives a good summary: https://donatstudios.com/Go-v2-Modules

We would need users to adopt new import paths, still support an old version, for what I believe are useful but minimal overall benefits to a pretty simple package.

**Comment by 123raoul123** [comment]
Hi Elithrar,
Thank you for your fast response, explanation and for sharing this interesting article.
I understand now that implementing a v2 is definitely non-trivial.
However when I look at your post from 2017: https://github.com/gorilla/sessions/issues/105 I see all these new plans for extending the store interface. On current day I still see that sessions still relies on maxAge to trigger a delete in the store.
That is why I was wondering if you needed help.

I saw that you closed #225. I was wondering on some advice regarding the following setup. What would the best approach be to  a microservice setup. There is a dedicated authentication service authenticating users creating a session and depositing these in the clustered database. The other services will look for the cookie and if absent plainly deny the request. Since the signature key is symmetric, I would either have to share this key with all my microservices or I should create a separate extractor to obtain the database ID from the database.
