### ISSUE TITLE
Invalidating Other Sessions (no concurrent logged-in users)

### ISSUE THREAD

**Issue by Zamiell** [gorilla/sessions#86]
First off, a thanks is in order - `gorilla/sessions` has excellent documentation and very helpful examples on the website. Thank you!

One seemingly common use-case that is not covered in the docs is the scenario of when a user logs in, all other sessions from that user should be invalidated. How is this supposed to be tacked using `gorilla/sessions`?

Here's a code snippet to illustrate the problem:

```
func loginHandler(w http.ResponseWriter, r *http.Request) {
	// Get the POSTed credentials
	// [omitted, just going to hardcode a username for now]
	username := "Fred"

	// Check the database to see if it is a valid login
	// [omitted, we checked the credentials and it passed, so we can proceed]

	// Establish a session cookie using gorilla/sessions
	session, _ := sessionStore.Get(r, sessionName)
	session.Values["logged_in"] = true
	session.Values["username"] = username
	session.Save(r, w)

	// Set "logged_in" equal to false for all other sessions with a username of username
	// [?????]
}
```

After some searching around, I did find the following GitHub issue that tangentially discusses this: https://github.com/gorilla/sessions/issues/67

However, I wasn't able to completely follow the discussion, as it implies that the programmer should create a custom Store implementation, and I'm fairly new to Golang.

Apart from this, one possible way that I thought of to solve this problem is to use the `michaeljs1990/sqlitestore` implementation of `gorilla/sessions`. Then, I could just iterate over the sessions in the table and manually mess with the session values for any row that matched the username. However, this seems a bit hacky, and I wonder if it is the "wrong" solution.

Thanks again for reading.

**Comment by elithrar** [comment]
- If you're using CookieStore: it does this for you, as the cookie name is
the key (and will be overwritten/only one cookie with that name can exist
for a given domain).
- If not, then you would need to track some other value (since the DB key,
in most server-side stores, is just a random generated ID)

Note that without a cookie to refer to the "old" session, it won't come
into play, lest the user (or an attacker) kept track of all previous
session IDs. This is incentive to keep expiries as short as reasonably
possible (and just refresh based on activity) and use HTTPS.

If you *do* want to track it, you would need to have a deterministic key.
I've done this with a related (but dissimilar) project for authenticating
users: the key is a hash of their user ID, and their underlying session ID
(32 bytes generated from crypto/rand) is associated with this as a value
(BoltDB, Redis hashmap, etc.).

e.g. cookie: sha256(userID) - server store: key = sha256(userID), value = {
sessionID, data }

Hope that's clear!

**Comment by Zamiell** [comment]
Thanks for the quick reply elithrar; unfortunately, it seems to be as clear as mud for me. =p

> - If you're using CookieStore: it does this for you, as the cookie name is
the key (and will be overwritten/only one cookie with that name can exist
for a given domain).

I am using CookieStore; my apologies for not specifying this in the original post. However, as per my testing, I have generated 2 cookies using `session, _ := sessionStore.Get(r, "isaac-sid")` and both cookies appear to continue to work just fine, getting past my `validateSession` function. Here's a code snippet that is slightly more verbose than what I posted in the original post:

```
var sessionStore = sessions.NewCookieStore([]byte("super-secret-key"))

func validateSession(w http.ResponseWriter, r *http.Request) bool {
	if session, err := sessionStore.Get(r, "isaac-sid"); err == nil { // Get session
		if v, ok := session.Values["logged_in"]; ok && v == true { // Check if session is authorized
			return true
		}
	}
	log.Debug("Unauthorized user detected:", r)
	return false;
}

func loginHandler(w http.ResponseWriter, r *http.Request) {
    // Get the POSTed credentials
    // [omitted, just going to hardcode a username for now]
    username := "Fred"

    // Check the database to see if it is a valid login
    // [omitted, we checked the credentials and it passed, so we can proceed]

    // Establish a session cookie using gorilla/sessions
    session, _ := sessionStore.Get(r, "isaac-sid")
    session.Values["logged_in"] = true
    session.Values["username"] = username
    session.Save(r, w)
```

Is this the expected behavior?

**Comment by elithrar** [comment]
What are the Path, Domain and Secure attributes of those cookies?

**Comment by Zamiell** [comment]
A valid login request gives me the following:

`Set-Cookie: isaac.sid=MTQ2Nzk4NTQxMXxEdi1CQkFFQ180SUFBUkFCRUFBQV80SF9nZ0FEQm5OMGNtbHVad3dMQUFsc2IyZG5aV1JmYVc0RVltOXZiQUlDQUFFR2MzUnlhVzVuREFvQUNHRjFkR2d3WDJsa0JuTjBjbWx1Wnd3Z0FCNWhkWFJvTUh3MU56YzNNRFppWXpJek5UTTNOR001TURabE5XWXhOR01HYzNSeWFXNW5EQW9BQ0hWelpYSnVZVzFsQm5OMGNtbHVad3dJQUFaNllXMXBaV3c9fP8jEjrF_bE1-4eFiJOOSWLToiY6IsREvi6HoXeHIe-j; Expires=Fri, 15 Jul 2016 13:43:31 GMT; Max-Age=604800; HttpOnly`

**Comment by Zamiell** [comment]
I've messed around with the cookie a little and even after setting all of that stuff, I still encounter the same functionality:

```
// Create a session store
sessionSecret := os.Getenv("SESSION_SECRET")
sessionStore = sessions.NewCookieStore([]byte(sessionSecret))
sessionStore.Options = &sessions.Options{
	Domain:   domainName,
	Path:     "/",
	MaxAge:   86400, // 1 day
	Secure:   true, // Only send the cookie over HTTPS: https://www.owasp.org/index.php/Testing_for_cookies_attributes_(OTG-SESS-002)
	HttpOnly: true, // Mitigate XSS attacks: https://www.owasp.org/index.php/HttpOnly
}
```

**Comment by elithrar** [comment]
I would definitely expect that "two" cookies would still be valid: you can only have one named cookie (for a given path/domain pair) at a time, if you copied the old cookie string it would pass validation until it expired. That's expected behaviour [for any cookie-based store, because you can't invalidate older cookies if you can't write over them directly].

The benefit of a server-side store is that you can only allow one session per user/track existing sessions and forcibly invalidate them per-user.

**Comment by Zamiell** [comment]
Gotcha. I see now that the important thing is:

> This is incentive to keep expiries as short as reasonably
possible (and just refresh based on activity) and use HTTPS.

For my use case (a Golem framework websocket server), I'll need to set a cookie expiry of 5 seconds or so. Users will use the cookie to establish a websocket connection. Once the websocket connection is established, it doesn't matter if the cookie is expired, because the connection will persist.

Then, during the connection establishment (`OnConnect` in the Golem framework), I can add the connection to a connection map with a key of their username, so that I can reference them and manually close them down later if need be. Furthermore, I use a `SetConnectionExtension` to store additional information in the session itself, like the username or the time that the connection was established.

Thanks again for guiding me in the right direction.
