### ISSUE TITLE
Are there any cookie size limitations?

### ISSUE THREAD

**Issue by danhardman** [gorilla/sessions#89]
I want to store a struct in a cookie value that's fairly large, I know that `encoding/gob` is used to encode structs, but I'm not sure how that affects the size of them when passed to the browser.

I know that browsers have a 4KB limit on cookies, so I'm worried the cookie I'm creating is too large. Already when the struct is in an "empty" state (useful fields have no value), the cookie is 1632 bytes.

Am I okay or should I look into storing them server side or passing a reference to what I want persisted to the cookie instead and use a database?

**Comment by danhardman** [comment]
Did things the proper way and decided to store the ID of the struct I wanted to persist in the cookie instead of storing the entire struct. Been a while since I've dealt with cookies so it just didn't occur to me that it might be a weird way of doing things!

Either way, would still be interesting to know about the cookie size limitations and how `encoding/gob` affects cookie size

**Comment by elithrar** [comment]
4KB is the limit, and gob does have overhead (due to the type metadata it must prepend), but there's also the timestamp and HMAC hash that add to the size. The JSON encoder can be faster and more compact, but it is less universal as not all types can be marshalled to JSON.

I'd have to to some testing and find a way to represent Go object -> sessions -> final size in a sensible way for users.

Keeping cookie data to a minimum would still be suggested regardless.

**Comment by danhardman** [comment]
I think a recommendation amongst the documentation on adding structs to `session.Values` to consider cookie size would be good.

When I was first considering keeping record of something client-side, I completely overlooked size limitations. Admittedly due to not working with cookies in so long, but a warning would have been good! Especially considering structs are likely to come close to the size limit very easily!
